### ISSUE TITLE
Typescript with remix-i18next

### ISSUE THREAD

**Issue by hyochan** [prisma-korea/prisma-remix-boilerplate#3]
As of https://github.com/prisma-korea/prisma-remix-boilerplate/commit/afd2592863d1f900bd30312791dccc31517b88c1, the typescript is not configured correctly so we can't autocomplete the types with `useTranslation`.

More info in https://github.com/prisma-korea/prisma-remix-boilerplate/pull/2/files#r1002664763

**Comment by hyochan** [comment]
> @hyochan
> 
> > we can't autocomplete the types with useTranslation
> 
> What does autocomplete mean? Does it mean the autocomplete in VSCode like the following? 🤔
> 
> ![Screen Shot 2022-10-24 at 21 19 21](https://user-images.githubusercontent.com/42969906/197524497-c6c1407a-b4ea-4911-9602-afca3612b95e.jpg)
> 
> ![Screen Shot 2022-10-24 at 21 20 05](https://user-images.githubusercontent.com/42969906/197524523-e8e4a8f2-18e1-485c-a660-e08b29716cc5.jpg)
> 
> If it does, I think it works well.
> 
> > As of [afd2592](https://github.com/prisma-korea/prisma-remix-boilerplate/commit/afd2592863d1f900bd30312791dccc31517b88c1),
> 
> And I think the link is wrong. 🤔 I can't find any clue about the issue in the link. 🔍

I am sorry for not making this clear enough and also thanks for trying out the solution.

Currently, we have two problems.

1. t('MY_STRING') is inferred as `object` so we need to [type cast](https://www.w3schools.com/typescript/typescript_casting.php) this to [as string](https://github.com/prisma-korea/prisma-remix-boilerplate/blob/main/app/routes/sign-in.tsx#L62).

2. Indeed, it'd be great if we could support auto-completion as we did in [react native](http://github.com/dooboolab/hackatalk) project. Example in the below screenshots.

    <img width="527" alt="auto_complete" src="https://user-images.githubusercontent.com/27461460/197675436-041f13bd-bdb1-4b5a-b748-0f0cd54879b3.png">

    <img width="834" alt="strings" src="https://user-images.githubusercontent.com/27461460/197675474-68e0d511-d387-4942-95da-e8094355dc01.png">

**Comment by dev-yakuza** [comment]
I found the TypeScript example.

- Example: https://github.com/i18next/react-i18next/tree/master/example/react-typescript4.1

And it works well.

| Namespaces | No namespaces |
| -- | -- |
| ![Screenshot 2022-11-01 at 22 18 48](https://user-images.githubusercontent.com/42969906/199242669-468c842d-60dd-4cf6-bdb7-2e9de5c62665.jpg) | ![Screenshot 2022-11-01 at 22 19 11](https://user-images.githubusercontent.com/42969906/199242726-71e4c0a4-fb59-4f2e-b59f-ff4e2d44c256.jpg) |

I try to compare the example and this repository to find the reason for the issue.
